// ============================================================
// KHADANE™ — Variety Catalogue Data · v1.0 locked
// 21 varieties: 12 owned (#KHD-001 to #KHD-013, ex-009)
//             + 9 allied (#KHD-009, #KHD-014 to #KHD-021)
// ============================================================

export type Tier = 'owned' | 'allied'

export interface Variety {
  code: string                    // #KHD-001
  rank: number                    // 1
  slug: string                    // kandla-grey
  name: string                    // Kandla Grey
  nameHindi: string               // कंदला ग्रे
  tier: Tier
  tierLabel: string               // "Owned & Operated" | "Allied · The Network"
  district: string                // Bhilwara District
  formation: string               // Vindhyan Supergroup, Bhander Group
  tradeNames: string              // Alt market names
  oneLine: string                 // Two-statement hero descriptor
  inHandHeadline: string          // Section A headline
  formatScope: string             // "All 14 formats" | "Blocks only" etc.
  formatExceptions?: string[]     // ["paving-not-available"] etc.
  placeholderClass: string        // CSS class for placeholder swatch
  ownedQuarryCount?: number       // For owned tier
  alliedRelationship?: string     // For allied tier — relationship description
  alternateNames?: string[]       // Trade-market alt names
}

export const VARIETIES: Variety[] = [
  // ─── OWNED & OPERATED (12) ───
  {
    code: '#KHD-001',
    rank: 1,
    slug: 'kandla-grey',
    name: 'Kandla Grey',
    nameHindi: 'कंदला ग्रे',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bhilwara District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Kandla, Grey Indian Sandstone, Mint Grey',
    oneLine: 'The most-shipped Indian sandstone. From quarries we own.',
    inHandHeadline: 'A working grey.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-grey',
    alternateNames: ['Mint Grey', 'Indian Grey'],
  },
  {
    code: '#KHD-002',
    rank: 2,
    slug: 'autumn-brown',
    name: 'Autumn Brown',
    nameHindi: 'ऑटम ब्राउन',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bhilwara District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Autumn, Indian Brown Sandstone',
    oneLine: 'The warm-brown anchor of the export catalogue. From quarries we own.',
    inHandHeadline: 'The warm brown.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone',
  },
  {
    code: '#KHD-003',
    rank: 3,
    slug: 'raj-green',
    name: 'Raj Green',
    nameHindi: 'राज ग्रीन',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bundi District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Raj Green, Indian Green Sandstone',
    oneLine: 'The mixed-tone green-brown landscape paving. From quarries we own.',
    inHandHeadline: 'The variegated green.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-green',
  },
  {
    code: '#KHD-004',
    rank: 4,
    slug: 'raj-blend',
    name: 'Raj Blend',
    nameHindi: 'राज ब्लेंड',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bundi District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Raj Blend, Mixed Indian Sandstone',
    oneLine: 'The brown-green paving blend for heritage projects. From quarries we own.',
    inHandHeadline: 'A multi-tone blend.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone',
  },
  {
    code: '#KHD-005',
    rank: 5,
    slug: 'garda-green',
    name: 'Garda Green',
    nameHindi: 'गारदा ग्रीन',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Kota District',
    formation: 'Vindhyan Supergroup',
    tradeNames: 'Garda Green, Deep Green Sandstone',
    oneLine: 'The deep-green landscape paving from Garda. From quarries we own.',
    inHandHeadline: 'A deeper green.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-green',
  },
  {
    code: '#KHD-006',
    rank: 6,
    slug: 'raveena-white',
    name: 'Raveena White',
    nameHindi: 'रवीना व्हाइट',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bhilwara District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Raveena, Indian White Sandstone',
    oneLine: 'The lighter neutral paving for contemporary patios. From quarries we own.',
    inHandHeadline: 'A neutral white.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-warm',
  },
  {
    code: '#KHD-007',
    rank: 7,
    slug: 'camel-dust',
    name: 'Camel Dust',
    nameHindi: 'कैमल डस्ट',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bhilwara District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Camel Dust, Rippon Buff, Desert Gold',
    oneLine: 'The buff-tone export favorite, also marketed as Rippon Buff. From quarries we own.',
    inHandHeadline: 'The desert tone.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-warm',
    alternateNames: ['Rippon Buff', 'Desert Gold'],
  },
  {
    code: '#KHD-008',
    rank: 8,
    slug: 'fossil-mint',
    name: 'Fossil Mint',
    nameHindi: 'फॉसिल मिंट',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Kota District',
    formation: 'Vindhyan Supergroup',
    tradeNames: 'Fossil Mint, Mint Fossil',
    oneLine: 'The mint-toned paving with distinctive fossil patterning. From quarries we own.',
    inHandHeadline: 'A fossil-marked stone.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-warm',
  },
  {
    code: '#KHD-009',
    rank: 9,
    slug: 'teakwood',
    name: 'Teakwood',
    nameHindi: 'टीकवुड',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Nagaur District',
    formation: 'Marwar Supergroup',
    tradeNames: 'Teakwood, Wood Grain Sandstone',
    oneLine: 'The premium wood-grain sandstone. Sourced direct from heritage operators.',
    inHandHeadline: 'A stone that reads as wood.',
    formatScope: 'Blocks only (#KHF-003)',
    formatExceptions: ['blocks-only'],
    placeholderClass: 'placeholder-stone',
    alliedRelationship: 'Sourced direct from a heritage operator in Nagaur District, processed for raw-block export only.',
  },
  {
    code: '#KHD-010',
    rank: 10,
    slug: 'rainbow',
    name: 'Rainbow',
    nameHindi: 'रेनबो',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bhilwara + Bundi Districts',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Rainbow, Indian Multi-Color Sandstone',
    oneLine: 'Multi-color banded paving for contemporary statement floors. From quarries we own.',
    inHandHeadline: 'A banded stone.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone',
  },
  {
    code: '#KHD-011',
    rank: 11,
    slug: 'dual-tone',
    name: 'Dual Tone',
    nameHindi: 'ड्यूल टोन',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bhilwara + Bundi Districts',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Dual Tone, Two-Tone Indian Sandstone',
    oneLine: 'Two-tone contemporary paving with natural striation. From quarries we own.',
    inHandHeadline: 'Two tones in one block.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone',
  },
  {
    code: '#KHD-012',
    rank: 12,
    slug: 'kaansiya-red',
    name: 'Kaansiya Red',
    nameHindi: 'कांसिया रेड',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bhilwara District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Kaansiya Red, Modak, Red Chocolate',
    oneLine: 'The red sandstone of the Bijolia belt, also marketed as Modak. From quarries we own.',
    inHandHeadline: 'A working red.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-red',
    alternateNames: ['Modak', 'Red Chocolate'],
  },
  {
    code: '#KHD-013',
    rank: 13,
    slug: 'slate-grey',
    name: 'Slate Grey',
    nameHindi: 'स्लेट ग्रे',
    tier: 'owned',
    tierLabel: 'Owned & Operated',
    district: 'Bhilwara District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Slate Grey, Dark Indian Sandstone',
    oneLine: 'The darker grey paving alternative for cooler projects. From quarries we own.',
    inHandHeadline: 'A deeper grey.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-grey',
  },

  // ─── ALLIED · THE NETWORK (8 more) ───
  {
    code: '#KHD-014',
    rank: 14,
    slug: 'agra-red',
    name: 'Agra Red',
    nameHindi: 'आगरा रेड',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Dholpur District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Agra Red, Indian Red Sandstone',
    oneLine: 'The red sandstone that built the Red Fort. Sourced direct from Dholpur.',
    inHandHeadline: 'The Mughal red.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-red',
    alliedRelationship: 'Sourced direct from heritage Dholpur operators. Processed and dispatched under DSI custody.',
  },
  {
    code: '#KHD-015',
    rank: 15,
    slug: 'jodhpur-chittar',
    name: 'Jodhpur Chittar',
    nameHindi: 'जोधपुर चित्तर',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Jodhpur District',
    formation: 'Marwar Supergroup',
    tradeNames: 'Jodhpur Chittar, Jodhpur Pink',
    oneLine: 'The pink sandstone of Mehrangarh. Sourced direct from Jodhpur.',
    inHandHeadline: 'The fort stone.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-warm',
    alternateNames: ['Jodhpur Pink'],
    alliedRelationship: 'Sourced direct from heritage Jodhpur operators in the Marwar belt.',
  },
  {
    code: '#KHD-016',
    rank: 16,
    slug: 'jaisalmer-yellow',
    name: 'Jaisalmer Yellow',
    nameHindi: 'जैसलमेर यलो',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Jaisalmer District',
    formation: 'Jurassic Jaisalmer Formation',
    tradeNames: 'Jaisalmer Yellow, Yellow Sandstone',
    oneLine: 'The yellow sandstone of Jaisalmer Fort. Sourced direct from Jaisalmer.',
    inHandHeadline: 'The desert yellow.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-warm',
    alliedRelationship: 'Sourced direct from heritage Jaisalmer operators. Jurassic-age formation, distinctive yellow.',
  },
  {
    code: '#KHD-017',
    rank: 17,
    slug: 'dholpur-pink',
    name: 'Dholpur Pink',
    nameHindi: 'धौलपुर पिंक',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Dholpur District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Dholpur Pink, Pink Sandstone',
    oneLine: 'The Mughal pink sandstone of Rajasthani palace heritage. Sourced direct from Dholpur.',
    inHandHeadline: 'The palace pink.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-warm',
    alliedRelationship: 'Sourced direct from heritage Dholpur operators.',
  },
  {
    code: '#KHD-018',
    rank: 18,
    slug: 'dholpur-beige',
    name: 'Dholpur Beige',
    nameHindi: 'धौलपुर बेज',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Dholpur District',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Dholpur Beige, Beige Sandstone',
    oneLine: 'The beige variant from Dholpur, for warm-tone paving. Sourced direct from Dholpur.',
    inHandHeadline: 'The beige variant.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-warm',
    alliedRelationship: 'Sourced direct from heritage Dholpur operators.',
  },
  {
    code: '#KHD-019',
    rank: 19,
    slug: 'sagar-black',
    name: 'Sagar Black',
    nameHindi: 'सागर ब्लैक',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Sagar District, Madhya Pradesh',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Sagar Black, Indian Black Sandstone',
    oneLine: 'The black sandstone of central India. Sourced direct from Sagar District.',
    inHandHeadline: 'A working black.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-yard',
    alliedRelationship: 'Sourced direct from heritage Sagar operators in Madhya Pradesh.',
  },
  {
    code: '#KHD-020',
    rank: 20,
    slug: 'lalitpur-yellow',
    name: 'Lalitpur Yellow',
    nameHindi: 'ललितपुर यलो',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Lalitpur District, Uttar Pradesh',
    formation: 'Vindhyan Supergroup, Bhander Group',
    tradeNames: 'Lalitpur Yellow, UP Yellow Sandstone',
    oneLine: 'The deep-yellow sandstone of UP for warm-tone paving. Sourced direct from Lalitpur.',
    inHandHeadline: 'A deeper yellow.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-warm',
    alliedRelationship: 'Sourced direct from heritage Lalitpur operators.',
  },
  {
    code: '#KHD-021',
    rank: 21,
    slug: 'mandana-red',
    name: 'Mandana Red',
    nameHindi: 'मंदाना रेड',
    tier: 'allied',
    tierLabel: 'Allied · The Network',
    district: 'Kota District',
    formation: 'Vindhyan Supergroup',
    tradeNames: 'Mandana Red, Mandana Sandstone',
    oneLine: 'The traditional red flooring stone of central Rajasthan. Sourced direct from Kota District.',
    inHandHeadline: 'A vernacular red.',
    formatScope: 'All 14 formats',
    placeholderClass: 'placeholder-stone-red',
    alliedRelationship: 'Sourced direct from heritage Kota District operators.',
  },
]

export function getVariety(slug: string): Variety | undefined {
  return VARIETIES.find((v) => v.slug === slug)
}

export function getOwnedVarieties(): Variety[] {
  return VARIETIES.filter((v) => v.tier === 'owned')
}

export function getAlliedVarieties(): Variety[] {
  return VARIETIES.filter((v) => v.tier === 'allied')
}

export function getPrevVariety(currentRank: number): Variety {
  const prevRank = currentRank === 1 ? VARIETIES.length : currentRank - 1
  return VARIETIES.find((v) => v.rank === prevRank)!
}

export function getNextVariety(currentRank: number): Variety {
  const nextRank = currentRank === VARIETIES.length ? 1 : currentRank + 1
  return VARIETIES.find((v) => v.rank === nextRank)!
}
