import {
  ENTITIES,
  FOUNDING,
  KHADANE_SCALE,
  LOCATIONS,
  MLS_SCALE,
  VERTICALS,
} from '@/lib/facts'
import { MINES_PORTFOLIO_FALLBACK } from '@/lib/khadane/mines-portfolio'
import type { AdminStore } from './types'

function iso(daysAgo = 0, hour = 10): string {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  d.setHours(hour, 14, 0, 0)
  return d.toISOString()
}

export function createSeedStore(): AdminStore {
  const now = new Date().toISOString()

  return {
    version: 1,
    lastSynced: now,
    operator: {
      name: 'Rahul Dhakar',
      role: 'Group Principal',
      initials: 'RD',
      location: 'Bijolia · Kota',
    },
    enquiries: [
      {
        id: 'enq_seed_1',
        reference: 'MLS-ENQ-SEED-88421',
        name: 'Harper Stone Ltd',
        email: 'buying@harperstone.example',
        phone: '+44 20 0000 0000',
        company: 'Harper Stone Ltd',
        country: 'United Kingdom',
        market: 'United Kingdom',
        vertical: 'Stone & Export',
        category: 'stone-export',
        site: 'khadane',
        subject: 'Kandla Grey 600×900 calibrated paving — 3 containers',
        message:
          'Requesting FOB Mundra quote for 3×20ft containers of Kandla Grey calibrated paving 600×900, 22mm. Delivery target Q3.',
        status: 'new',
        priority: 'high',
        owner: 'Export desk',
        notes: '',
        variety: 'Kandla Grey',
        format: 'Paving',
        volume: '3 containers',
        source: 'seed',
        createdAt: iso(0, 8),
        updatedAt: iso(0, 8),
      },
      {
        id: 'enq_seed_2',
        reference: 'MLS-ENQ-SEED-88418',
        name: 'Allen Career — Parent liaison',
        email: 'parent@example.com',
        phone: '+91 90000 00000',
        company: '',
        country: 'India',
        market: 'Kota',
        vertical: 'Student Housing',
        category: 'student-housing',
        site: 'mls',
        subject: 'Victoria Palace — twin occupancy for NEET session',
        message: 'Looking for twin occupancy for daughter for the upcoming NEET session.',
        status: 'in_review',
        priority: 'medium',
        owner: 'Housing desk',
        notes: 'Waitlist check needed',
        variety: '',
        format: '',
        volume: '',
        source: 'seed',
        createdAt: iso(1, 19),
        updatedAt: iso(1, 19),
      },
      {
        id: 'enq_seed_3',
        reference: 'MLS-ENQ-SEED-88412',
        name: 'Desert Pearl Contracting',
        email: 'procurement@desertpearl.example',
        phone: '+971 50 000 0000',
        company: 'Desert Pearl Contracting',
        country: 'United Arab Emirates',
        market: 'UAE',
        vertical: 'Stone & Export',
        category: 'stone-export',
        site: 'khadane',
        subject: 'Gangsaw slabs — Autumn Brown, 5cm, CIF Jebel Ali',
        message: 'Need CIF Jebel Ali pricing for Autumn Brown gangsaw slabs, 5cm thickness.',
        status: 'quoted',
        priority: 'high',
        owner: 'Export desk',
        notes: 'Proforma drafted',
        variety: 'Autumn Brown',
        format: 'Gangsaw Slabs',
        volume: '1,850 m²',
        source: 'seed',
        createdAt: iso(1, 11),
        updatedAt: iso(0, 9),
      },
      {
        id: 'enq_seed_4',
        reference: 'MLS-ENQ-SEED-88405',
        name: 'Corporate retreat — Jaipur',
        email: 'events@corp.example',
        phone: '+91 98000 00000',
        company: 'Corporate Events Desk',
        country: 'India',
        market: 'India',
        vertical: 'Hospitality',
        category: 'hospitality',
        site: 'mls',
        subject: 'M3 Boutique — 22 rooms, 3 nights, conference day',
        message: 'Group booking for 22 rooms with one conference day.',
        status: 'won',
        priority: 'medium',
        owner: 'M3 front office',
        notes: 'Deposit received',
        variety: '',
        format: '',
        volume: '22 rooms',
        source: 'seed',
        createdAt: iso(2, 16),
        updatedAt: iso(1, 12),
      },
      {
        id: 'enq_seed_5',
        reference: 'MLS-ENQ-SEED-88397',
        name: 'Fleet operator — Bundi corridor',
        email: 'fleet@operator.example',
        phone: '+91 97000 00000',
        company: 'Bundi Fleet Co',
        country: 'India',
        market: 'Rajasthan',
        vertical: 'Automotive & Fuel',
        category: 'automotive',
        site: 'mls',
        subject: 'Commercial service package + bulk fuel account',
        message: 'Interested in commercial service package and bulk fuel account.',
        status: 'in_review',
        priority: 'low',
        owner: 'Dhakar Motors',
        notes: '',
        variety: '',
        format: '',
        volume: '',
        source: 'seed',
        createdAt: iso(2, 9),
        updatedAt: iso(2, 9),
      },
      {
        id: 'enq_seed_6',
        reference: 'MLS-ENQ-SEED-88391',
        name: 'Campus mess tender',
        email: 'campus@example.com',
        phone: '+91 96000 00000',
        company: 'Campus Admin',
        country: 'India',
        market: 'Kota',
        vertical: 'Food Services',
        category: 'food-services',
        site: 'mls',
        subject: 'Vyanjanam capacity for 180 additional evening meals',
        message: 'Can Vyanjanam absorb 180 additional evening meals from next month?',
        status: 'new',
        priority: 'medium',
        owner: 'Divine Food Services',
        notes: '',
        variety: '',
        format: '',
        volume: '180 meals',
        source: 'seed',
        createdAt: iso(3, 21),
        updatedAt: iso(3, 21),
      },
    ],
    shipments: [
      {
        id: 'shp_1',
        code: 'SH-2607-0184',
        destination: 'Felixstowe, UK',
        variety: 'Kandla Grey · Paving',
        status: 'in_transit',
        eta: '2026-07-28',
        volume: '2,400 m²',
        port: KHADANE_SCALE.port,
        buyer: 'Harper Stone Ltd',
        notes: '',
        createdAt: iso(10, 10),
        updatedAt: iso(1, 10),
      },
      {
        id: 'shp_2',
        code: 'SH-2607-0179',
        destination: 'Jebel Ali, UAE',
        variety: 'Autumn Brown · Slabs',
        status: 'loading',
        eta: '2026-07-18',
        volume: '1,850 m²',
        port: KHADANE_SCALE.port,
        buyer: 'Desert Pearl Contracting',
        notes: 'Container seal pending',
        createdAt: iso(8, 10),
        updatedAt: iso(0, 11),
      },
      {
        id: 'shp_3',
        code: 'SH-2607-0171',
        destination: 'Rotterdam, NL',
        variety: 'Sage Green · Tiles',
        status: 'cleared_customs',
        eta: '2026-07-12',
        volume: '3,120 m²',
        port: KHADANE_SCALE.port,
        buyer: 'EuroPave BV',
        notes: '',
        createdAt: iso(20, 10),
        updatedAt: iso(2, 10),
      },
      {
        id: 'shp_4',
        code: 'SH-2607-0162',
        destination: 'Sydney, AU',
        variety: 'Raveena White · Cladding',
        status: 'delivered',
        eta: '2026-07-04',
        volume: '980 m²',
        port: KHADANE_SCALE.port,
        buyer: 'Southern Stone Co',
        notes: 'POD filed',
        createdAt: iso(35, 10),
        updatedAt: iso(9, 10),
      },
      {
        id: 'shp_5',
        code: 'SH-2607-0155',
        destination: 'Houston, US',
        variety: 'Raj Blend · Cobbles',
        status: 'in_transit',
        eta: '2026-08-02',
        volume: '1,640 m²',
        port: KHADANE_SCALE.port,
        buyer: 'Gulf Masonry LLC',
        notes: '',
        createdAt: iso(12, 10),
        updatedAt: iso(3, 10),
      },
    ],
    alerts: [
      {
        id: 'alt_1',
        level: 'critical',
        title: 'Monsoon contingency — Bijolia yard',
        body: 'Rainfall advisory active. Covered stock rotation scheduled.',
        status: 'open',
        owner: 'Yard operations',
        createdAt: iso(0, 7),
        updatedAt: iso(0, 7),
      },
      {
        id: 'alt_2',
        level: 'info',
        title: 'New buyer onboarding — UK',
        body: 'Harper Stone Ltd credit check complete. Desk ready to quote.',
        status: 'open',
        owner: 'Export desk',
        createdAt: iso(0, 8),
        updatedAt: iso(0, 8),
      },
      {
        id: 'alt_3',
        level: 'warn',
        title: 'Occupancy spike — The Princess',
        body: 'Waitlist at 28 for August NEET cycle. Overflow protocol draft ready.',
        status: 'acknowledged',
        owner: 'Housing desk',
        createdAt: iso(1, 10),
        updatedAt: iso(0, 14),
      },
    ],
    tasks: [
      {
        id: 'tsk_1',
        title: 'Issue proforma for Desert Pearl',
        description: 'Autumn Brown gangsaw slabs CIF Jebel Ali',
        status: 'in_progress',
        priority: 'high',
        owner: 'Export desk',
        dueDate: iso(0, 18).slice(0, 10),
        relatedEnquiryId: 'enq_seed_3',
        createdAt: iso(1, 12),
        updatedAt: iso(0, 9),
      },
      {
        id: 'tsk_2',
        title: 'Confirm Victoria Palace twin inventory',
        description: 'NEET session demand check',
        status: 'todo',
        priority: 'medium',
        owner: 'Housing desk',
        dueDate: iso(-1, 12).slice(0, 10),
        relatedEnquiryId: 'enq_seed_2',
        createdAt: iso(1, 20),
        updatedAt: iso(1, 20),
      },
      {
        id: 'tsk_3',
        title: 'Yard monsoon cover audit',
        description: 'Walk covered stock bays A–D',
        status: 'todo',
        priority: 'high',
        owner: 'Yard operations',
        dueDate: iso(0, 17).slice(0, 10),
        relatedEnquiryId: '',
        createdAt: iso(0, 7),
        updatedAt: iso(0, 7),
      },
    ],
    activity: [
      {
        id: 'act_1',
        actor: 'System',
        action: 'Command centre store initialised with seed operations data',
        entityType: 'system',
        entityId: '',
        createdAt: now,
      },
      {
        id: 'act_2',
        actor: 'Export desk',
        action: 'Quoted ENQ MLS-ENQ-SEED-88412 (Desert Pearl)',
        entityType: 'enquiry',
        entityId: 'enq_seed_3',
        createdAt: iso(0, 9),
      },
      {
        id: 'act_3',
        actor: 'Yard operations',
        action: 'Shipment SH-2607-0179 marked loading at Mundra',
        entityType: 'shipment',
        entityId: 'shp_2',
        createdAt: iso(0, 11),
      },
      {
        id: 'act_4',
        actor: 'Housing desk',
        action: 'Acknowledged alert: Occupancy spike — The Princess',
        entityType: 'alert',
        entityId: 'alt_3',
        createdAt: iso(0, 14),
      },
    ],
    verticals: VERTICALS.map((v, i) => {
      const rows = [
        {
          revenue: '₹248.4 Cr',
          share: 58,
          status: 'on_track' as const,
          sites: `${KHADANE_SCALE.quarries} quarries`,
          headcount: KHADANE_SCALE.workforce,
          highlight: KHADANE_SCALE.annualOutput,
          region: 'Rajasthan · Mundra · 20+ countries',
        },
        {
          revenue: '₹62.1 Cr',
          share: 14.5,
          status: 'stable' as const,
          sites: `${MLS_SCALE.dharnidharStations} · Dabi workshop`,
          headcount: '180+',
          highlight: `Since ${MLS_SCALE.dhakarMotorsOpened}`,
          region: LOCATIONS.dhakarMotorsLocation,
        },
        {
          revenue: '₹41.8 Cr',
          share: 9.8,
          status: 'growing' as const,
          sites: 'M3 Hotel + Mini Mall',
          headcount: '95+',
          highlight: `${MLS_SCALE.m3Rooms} · Opened ${MLS_SCALE.m3Opened}`,
          region: 'Kunhari, Kota',
        },
        {
          revenue: '₹48.6 Cr',
          share: 11.3,
          status: 'on_track' as const,
          sites: '2 girls campuses · 3 boys PGs',
          headcount: '120+',
          highlight: MLS_SCALE.studentHousingTotal,
          region: 'Kunhari campus · Kota',
        },
        {
          revenue: '₹27.7 Cr',
          share: 6.4,
          status: 'watch' as const,
          sites: 'Vyanjanam · Divine Dining',
          headcount: '140+',
          highlight: MLS_SCALE.vyanjanamDailyMeals,
          region: 'Kota · Bijolia dairy chain',
        },
      ][i]!

      return {
        id: `vert_${v.slug}`,
        slug: v.slug,
        title: v.title,
        brand: v.brand,
        framing: v.framing,
        notes: '',
        updatedAt: now,
        ...rows,
      }
    }),
    sites: [
      {
        id: 'site_bijolia',
        name: 'Bijolia HQ & quarries',
        role: LOCATIONS.bijolia.role,
        coords: LOCATIONS.bijolia.coords,
        status: 'operational',
        people: '620+',
        focus: 'Stone · dairy · fuels · family base',
        notes: '',
        updatedAt: now,
      },
      {
        id: 'site_kunhari',
        name: 'Kunhari campus (Kota)',
        role: LOCATIONS.kunhari,
        coords: LOCATIONS.kota.coords,
        status: 'operational',
        people: '280+',
        focus: 'Housing · hotel · food · mini mall',
        notes: '',
        updatedAt: now,
      },
      {
        id: 'site_dabi',
        name: 'Dhakar Motors (Dabi)',
        role: LOCATIONS.dhakarMotorsLocation,
        coords: '25°26′N · 75°38′E',
        status: 'operational',
        people: '90+',
        focus: 'Automotive service',
        notes: '',
        updatedAt: now,
      },
      {
        id: 'site_fuels',
        name: 'Dharnidhar Fuels',
        role: LOCATIONS.dharnidharFuelsLocation,
        coords: 'NH-27 corridor',
        status: 'operational',
        people: '40+',
        focus: 'Retail fuel · two stations',
        notes: '',
        updatedAt: now,
      },
      {
        id: 'site_mundra',
        name: 'Mundra port corridor',
        role: LOCATIONS.mundra.role,
        coords: LOCATIONS.mundra.coords,
        status: 'active_shipping',
        people: 'Field team',
        focus: 'KHADANE export loading',
        notes: '',
        updatedAt: now,
      },
    ],
    mines: MINES_PORTFOLIO_FALLBACK,
    ceoPlans: [
      {
        id: 'plan_rev_group',
        title: 'Group stone revenue lift',
        category: 'revenue',
        metricLabel: 'Stone vertical revenue',
        unit: '₹ Cr',
        presentValue: 248,
        futureValue: 320,
        horizon: 'FY 2027–28',
        status: 'active',
        owner: 'Group principal',
        notes: 'Grow export mix and allied offtake without diluting grade control.',
        linkedMineId: 'mine_bijolia_main',
        milestones: [
          {
            id: 'ms1',
            label: 'UK market page + 2 containers pipeline',
            targetDate: '2026-12-31',
            done: false,
          },
          {
            id: 'ms2',
            label: 'Bundi face throughput +12%',
            targetDate: '2027-03-31',
            done: false,
          },
        ],
        createdAt: now,
        updatedAt: now,
        createdBy: 'System',
      },
      {
        id: 'plan_export_countries',
        title: 'Active export markets',
        category: 'export',
        metricLabel: 'Paying markets',
        unit: 'countries',
        presentValue: 20,
        futureValue: 28,
        horizon: 'FY 2027–28',
        status: 'active',
        owner: 'Export desk',
        notes: 'Focus AU + SE Asia without thinning UK service levels.',
        linkedMineId: '',
        milestones: [],
        createdAt: now,
        updatedAt: now,
        createdBy: 'System',
      },
      {
        id: 'plan_workforce_yard',
        title: 'Yard + quarry skilled crew',
        category: 'workforce',
        metricLabel: 'Stone workforce',
        unit: 'people',
        presentValue: 500,
        futureValue: 620,
        horizon: 'Dec 2027',
        status: 'active',
        owner: 'Yard operations',
        notes: 'Training hours and monsoon contingency staffing.',
        linkedMineId: 'mine_bijolia_main',
        milestones: [],
        createdAt: now,
        updatedAt: now,
        createdBy: 'System',
      },
      {
        id: 'plan_jaisalmer',
        title: 'Jaisalmer yellow — commercial offtake',
        category: 'mines',
        metricLabel: 'Commercial readiness score',
        unit: '%',
        presentValue: 15,
        futureValue: 80,
        horizon: 'FY 2028–29',
        status: 'draft',
        owner: 'Group principal',
        notes: 'Prospect → sample → first commercial lot.',
        linkedMineId: 'mine_jaisalmer_edge',
        milestones: [
          {
            id: 'ms3',
            label: 'Full sample set to export desk',
            targetDate: '2026-10-01',
            done: false,
          },
        ],
        createdAt: now,
        updatedAt: now,
        createdBy: 'System',
      },
      {
        id: 'plan_capex_calibration',
        title: 'Calibration line capacity',
        category: 'capex',
        metricLabel: 'Daily calibrated m²',
        unit: 'm²/day',
        presentValue: 1200,
        futureValue: 2000,
        horizon: 'FY 2027–28',
        status: 'at_risk',
        owner: 'Yard operations',
        notes: 'Depends on Kota edge equipment schedule.',
        linkedMineId: 'mine_kota_edge',
        milestones: [],
        createdAt: now,
        updatedAt: now,
        createdBy: 'System',
      },
    ],
  }
}

export const ENTITY_STRIP = [
  ENTITIES.group.name,
  ENTITIES.khadane.name,
  ENTITIES.m3.hotel,
  ENTITIES.vyanjanam.brand,
  ENTITIES.dhakarMotors,
  ENTITIES.dharnidharFuels,
] as const

export const GROUP_META = {
  founded: FOUNDING.groupYear,
  yearsEvergreen: FOUNDING.yearsEvergreen,
  verticalsDisplay: MLS_SCALE.verticalsDisplay,
  workforce: MLS_SCALE.groupWorkforce,
  family: MLS_SCALE.familyMembers,
  countries: KHADANE_SCALE.countries,
  annualOutput: KHADANE_SCALE.annualOutput,
  studentBeds: MLS_SCALE.studentHousingTotal,
  meals: '1,000+',
} as const
